### ISSUE TITLE
Call pricing

### ISSUE THREAD

**Issue by seemk** [antdvid/FastAmericanOptionPricing#1]
Hi,

Great work!

From the project's read-me: `Extending to call option is not that straightforward and the call-put symmetry should not be used`.

Why is this the case? In the paper they remark that this method can be extended to calls via the symmetry - but I currently know too little about this topic. :smile: 

Thanks!

**Comment by QuantJoe** [comment]
Hi there Siim,

There are some bugs in that script, I've attached a version with some of
these resolved.  Still have some stability issues with the Calls, I want to
say I found a resolution to it but can't recall.  I worked on this about a
year ago, with the objective to incorporate discrete dividends, but didn't
end up accomplishing that goal.  If I recall correctly I had to find
the optimal exercise points for discrete dividends, where the derivatives
become discontinuities, and that was a bit much so I moved to a different
method.  I can't remember what all I did back then, but attached is some of
the work.  Let me know if you have any luck on it.  My code is a bit of a
mess, never intended to share it, but figured it might be of some help to
you.  If you review the "Spectral_american_npwraps" you'll find the correct
call and put formula's as well as their derivatives all worked out.  I
found method A more stable than method B.  Let me know if you have any
questions.  Best of luck.

Kind Regards
Joe
Joe.w.armstrong2@gmail.com

**Comment by seemk** [comment]
Thanks for the help, appreciate it. :slightly_smiling_face:  I think the attachments won't appear here if you reply via e-mail and I had e-mail notifications turned off (but even then I'm not sure attachments will come through GitHub) thus I can't find any. If you don't want to upload them here, then my e-mail is siimkallas@gmail.com

**Comment by antdvid** [comment]
The code actu

> Hi,
> 
> Great work!
> 
> From the project's read-me: `Extending to call option is not that straightforward and the call-put symmetry should not be used`.
> 
> Why is this the case? In the paper they remark that this method can be extended to calls via the symmetry - but I currently know too little about this topic. 😄
> 
> Thanks!

The code in the repository has already considered the call and put cases. What I mean in the readme is that the original paper doesn't give the formula for the call case. To get the call option formula, we need to derive from the very beginning. It is not straightforward, but I believe it's easy if you understand the derivation in the paper.
